/**
 * Skill Tree — Predefined Skill Nodes
 *
 * ~45 skills across 7 categories representing the full SCC capability map.
 * Dependencies form a DAG that can have cross-category links.
 */

import type { SkillTreeNode, CategoryMeta } from "./types";

// ---------------------------------------------------------------------------
// Category metadata
// ---------------------------------------------------------------------------

export const CATEGORIES: CategoryMeta[] = [
  {
    id: "foundation",
    name: "Foundation",
    nameZh: "基建",
    icon: "Blocks",
    color: "text-slate-400",
    glowColor: "#94a3b8",
    bgGradient: "from-slate-800 to-slate-900",
  },
  {
    id: "coding",
    name: "Coding",
    nameZh: "编程",
    icon: "Code2",
    color: "text-blue-400",
    glowColor: "#60a5fa",
    bgGradient: "from-blue-900 to-blue-950",
  },
  {
    id: "research",
    name: "Research",
    nameZh: "科研",
    icon: "FlaskConical",
    color: "text-purple-400",
    glowColor: "#c084fc",
    bgGradient: "from-purple-900 to-purple-950",
  },
  {
    id: "management",
    name: "Management",
    nameZh: "管理",
    icon: "Settings2",
    color: "text-amber-400",
    glowColor: "#fbbf24",
    bgGradient: "from-amber-900 to-amber-950",
  },
  {
    id: "creative",
    name: "Creative",
    nameZh: "创意",
    icon: "Palette",
    color: "text-pink-400",
    glowColor: "#f472b6",
    bgGradient: "from-pink-900 to-pink-950",
  },
  {
    id: "integration",
    name: "Integration",
    nameZh: "集成",
    icon: "Plug",
    color: "text-green-400",
    glowColor: "#4ade80",
    bgGradient: "from-green-900 to-green-950",
  },
  {
    id: "advanced",
    name: "Advanced",
    nameZh: "高级",
    icon: "Sparkles",
    color: "text-orange-400",
    glowColor: "#fb923c",
    bgGradient: "from-orange-900 to-orange-950",
  },
  {
    id: "other",
    name: "Other",
    nameZh: "其他",
    icon: "MoreHorizontal",
    color: "text-zinc-400",
    glowColor: "#a1a1aa",
    bgGradient: "from-zinc-800 to-zinc-900",
  },
];

// ---------------------------------------------------------------------------
// Skill nodes
// ---------------------------------------------------------------------------

export const SKILL_TREE_NODES: SkillTreeNode[] = [
  // ==================== FOUNDATION ====================
  {
    id: "claude-code",
    name: "Claude Code CLI",
    nameZh: "Claude Code CLI",
    description: "The core AI coding assistant CLI",
    descriptionZh: "核心 AI 编程助手 CLI",
    category: "foundation",
    defaultStatus: "active",
    icon: "Terminal",
    implType: "cli",
    implDetail: "claude --version",
    dependencies: [],
    tier: 1,
    tags: ["core", "cli"],
  },
  {
    id: "codex-cli",
    name: "Codex CLI",
    nameZh: "Codex CLI",
    description: "OpenAI Codex CLI for alternative AI provider",
    descriptionZh: "OpenAI Codex CLI 替代 AI 供应商",
    category: "foundation",
    defaultStatus: "configurable",
    icon: "Cpu",
    implType: "cli",
    implDetail: "codex --version",
    dependencies: [],
    tier: 1,
    tags: ["core", "cli", "openai"],
    detectCommand: "codex --version",
    setupSteps: [
      "Windows/Linux: npm install -g @openai/codex",
      "Set OPENAI_API_KEY environment variable (Windows: setx / Linux: export)",
      "Verify: codex --version",
    ],
    detectHint: "Run 'codex --version' in terminal",
    usageExample: "In Chat page, switch provider to Codex. Or use terminal: codex 'explain this code'",
    usageExampleZh: "在聊天页面切换提供者为 Codex，或在终端使用：codex 'explain this code'",
  },
  {
    id: "git",
    name: "Git",
    nameZh: "Git 版本控制",
    description: "Version control system",
    descriptionZh: "版本控制系统",
    category: "foundation",
    defaultStatus: "active",
    icon: "GitBranch",
    implType: "cli",
    dependencies: [],
    tier: 1,
    tags: ["core"],
  },
  {
    id: "nodejs",
    name: "Node.js",
    nameZh: "Node.js 运行时",
    description: "JavaScript runtime for dashboard and tools",
    descriptionZh: "Dashboard 和工具的运行环境",
    category: "foundation",
    defaultStatus: "active",
    icon: "Hexagon",
    implType: "cli",
    dependencies: [],
    tier: 1,
    tags: ["core", "runtime"],
  },
  {
    id: "python",
    name: "Python",
    nameZh: "Python 环境",
    description: "Python runtime for research scripts and ML",
    descriptionZh: "科研脚本和 ML 的运行环境",
    category: "foundation",
    defaultStatus: "active",
    icon: "FileCode",
    implType: "cli",
    dependencies: [],
    tier: 1,
    tags: ["core", "runtime", "ml"],
  },
  {
    id: "scc-dashboard",
    name: "SCC Dashboard",
    nameZh: "SCC 仪表盘",
    description: "The Super Claude Code web dashboard",
    descriptionZh: "Super Claude Code 网页管理面板",
    category: "foundation",
    defaultStatus: "active",
    icon: "LayoutDashboard",
    implType: "plugin",
    implDetail: "npm run dev",
    dependencies: ["nodejs", "claude-code"],
    tier: 2,
    tags: ["core", "ui"],
    pageRoute: "/",
    usageExample: "Open http://localhost:3000 in your browser to access the dashboard",
    usageExampleZh: "在浏览器中打开 http://localhost:3000 访问仪表盘",
  },
  {
    id: "mcp-servers",
    name: "MCP Servers",
    nameZh: "MCP 服务器",
    description: "Model Context Protocol server infrastructure",
    descriptionZh: "模型上下文协议服务器基础设施",
    category: "foundation",
    defaultStatus: "active",
    icon: "Server",
    implType: "mcp",
    implDetail: "~/.claude/settings.json → mcpServers",
    dependencies: ["claude-code"],
    tier: 2,
    tags: ["core", "mcp"],
    pageRoute: "/toolbox",
    usageExample: "Go to Toolbox > MCP tab to view and manage MCP servers. Add new servers with the '+' button.",
    usageExampleZh: "前往工具箱 > MCP 标签页查看和管理 MCP 服务器，点击 '+' 按钮添加新服务器。",
  },

  // ==================== CODING ====================
  {
    id: "tdd",
    name: "Test-Driven Dev",
    nameZh: "测试驱动开发",
    description: "Write tests first, then implement",
    descriptionZh: "先写测试，再实现功能",
    category: "coding",
    defaultStatus: "active",
    icon: "TestTube",
    implType: "skill",
    implDetail: "/tdd",
    dependencies: ["claude-code"],
    tier: 2,
    tags: ["testing", "methodology"],
  },
  {
    id: "code-review",
    name: "Code Review",
    nameZh: "代码审查",
    description: "Automated code quality review",
    descriptionZh: "自动化代码质量审查",
    category: "coding",
    defaultStatus: "active",
    icon: "SearchCode",
    implType: "skill",
    implDetail: "/code-review",
    dependencies: ["claude-code"],
    tier: 2,
    tags: ["quality"],
  },
  {
    id: "refactoring",
    name: "Refactoring",
    nameZh: "重构清理",
    description: "Dead code cleanup and consolidation",
    descriptionZh: "死代码清理和合并",
    category: "coding",
    defaultStatus: "active",
    icon: "Recycle",
    implType: "skill",
    implDetail: "/refactor-clean",
    dependencies: ["claude-code"],
    tier: 2,
    tags: ["quality", "cleanup"],
  },
  {
    id: "e2e-testing",
    name: "E2E Testing",
    nameZh: "端到端测试",
    description: "Playwright-based E2E test generation",
    descriptionZh: "基于 Playwright 的端到端测试生成",
    category: "coding",
    defaultStatus: "configurable",
    icon: "MonitorCheck",
    implType: "skill",
    implDetail: "/e2e",
    dependencies: ["claude-code", "nodejs"],
    tier: 3,
    tags: ["testing", "playwright"],
    setupSteps: [
      "npm install -D @playwright/test",
      "npx playwright install",
      "Create playwright.config.ts in project root",
    ],
    detectCommand: "npx playwright --version",
    detectHint: "Run 'npx playwright --version' in project",
  },
  {
    id: "security-scan",
    name: "Security Scan",
    nameZh: "安全扫描",
    description: "Vulnerability detection and remediation",
    descriptionZh: "漏洞检测和修复",
    category: "coding",
    defaultStatus: "active",
    icon: "Shield",
    implType: "skill",
    implDetail: "/security-scan",
    dependencies: ["claude-code"],
    tier: 3,
    tags: ["security"],
  },
  {
    id: "continuous-learning",
    name: "Continuous Learning",
    nameZh: "持续学习",
    description: "Extract patterns from sessions into reusable skills",
    descriptionZh: "从会话中提取模式为可复用技能",
    category: "coding",
    defaultStatus: "active",
    icon: "Brain",
    implType: "skill",
    implDetail: "/learn",
    dependencies: ["claude-code"],
    tier: 3,
    tags: ["meta", "skills"],
    setupSteps: [
      "Already bundled with Claude Code — use /learn in any session",
      "Windows/Linux: Type /learn in Claude Code to extract patterns from current session",
      "Learned skills are saved to ~/.claude/skills/",
    ],
    detectCommand: "claude --version",
    detectHint: "If Claude Code is installed, /learn is available — just type it in a session",
  },

  // ==================== RESEARCH ====================
  {
    id: "aris-pipeline",
    name: "ARIS Pipeline",
    nameZh: "ARIS 研究流水线",
    description: "Autonomous ML research pipeline with visual editor",
    descriptionZh: "自主 ML 研究流水线，可视化编辑器",
    category: "research",
    defaultStatus: "active",
    icon: "FlaskConical",
    implType: "plugin",
    implDetail: "ARIS Research plugin",
    dependencies: ["claude-code", "scc-dashboard"],
    tier: 2,
    tags: ["ml", "autonomous"],
    pageRoute: "/plugins/aris-research",
    usageExample: "Open ARIS Research page, pick a template or create a custom pipeline, then click Execute.",
    usageExampleZh: "打开 ARIS 研究页面，选择模板或创建自定义流水线，然后点击执行。",
  },
  {
    id: "lit-survey",
    name: "Literature Survey",
    nameZh: "文献调研",
    description: "Multi-source paper search and analysis",
    descriptionZh: "多源论文搜索与分析",
    category: "research",
    defaultStatus: "active",
    icon: "BookOpen",
    implType: "skill",
    implDetail: "/research-lit",
    dependencies: ["aris-pipeline"],
    tier: 3,
    tags: ["papers", "survey"],
  },
  {
    id: "idea-generation",
    name: "Idea Generation",
    nameZh: "想法生成",
    description: "Brainstorm research ideas with LLM validation",
    descriptionZh: "用 LLM 验证的头脑风暴研究想法",
    category: "research",
    defaultStatus: "active",
    icon: "Lightbulb",
    implType: "skill",
    implDetail: "/idea-creator",
    dependencies: ["lit-survey"],
    tier: 3,
    tags: ["ideas", "brainstorm"],
  },
  {
    id: "experiment-runner",
    name: "Experiment Runner",
    nameZh: "实验执行",
    description: "Deploy and run ML experiments on GPU servers",
    descriptionZh: "在 GPU 服务器上部署和运行 ML 实验",
    category: "research",
    defaultStatus: "configurable",
    icon: "Zap",
    implType: "skill",
    implDetail: "/run-experiment",
    dependencies: ["aris-pipeline", "python"],
    tier: 4,
    tags: ["ml", "gpu", "training"],
    setupSteps: [
      "Configure SSH access to GPU servers (Windows: C:\\Users\\<you>\\.ssh\\config | Linux: ~/.ssh/config)",
      "Verify SSH connectivity: ssh <host> 'nvidia-smi' (should show GPU info)",
      "Install ARIS skills: ensure ~/.claude/skills/run-experiment/ exists",
      "Set up persistent sessions: use 'screen' or 'tmux' on remote server",
      "Sync code to server: rsync -avz local/ remote:/path/to/code/",
    ],
    detectCommand: "ssh -o ConnectTimeout=5 -o BatchMode=yes ${sshHost} echo ok",
    detectHint: "SSH config must have GPU server entries. Check: Windows C:\\Users\\<you>\\.ssh\\config | Linux ~/.ssh/config",
    setupGuide: "Requires SSH access to GPU servers",
    configFields: [
      {
        key: "sshHost",
        label: "SSH Host",
        labelZh: "SSH 服务器",
        type: "select",
        allowCustom: true,
        placeholder: "user@host -p port",
        defaultValue: "thu_lc_2_chenyuxuan_2222",
        options: [
          { value: "thu_lc_2_chenyuxuan_2222", label: "A800-022 (8×A800, port 2222)", labelZh: "A800-022 (8×A800, 端口 2222)" },
          { value: "thu_lc_2_chenyuxuan_2290", label: "A800-090 (8×A800, port 2290)", labelZh: "A800-090 (8×A800, 端口 2290)" },
          { value: "thu_lc_chenyuxuan_2240", label: "A800-040 (8×A800, port 2240)", labelZh: "A800-040 (8×A800, 端口 2240)" },
          { value: "AI4S", label: "AI4S (106.63.100.80:11013)", labelZh: "AI4S (106.63.100.80:11013)" },
        ],
      },
      {
        key: "remoteDir",
        label: "Remote Code Directory",
        labelZh: "远程代码目录",
        type: "text",
        placeholder: "/mnt/qiyun/code/cyx/",
        defaultValue: "/mnt/qiyun/code/cyx/",
      },
      {
        key: "condaEnv",
        label: "Conda Environment",
        labelZh: "Conda 环境",
        type: "text",
        placeholder: "base",
        defaultValue: "base",
      },
    ],
    usageExample: "ssh <host> 'nvidia-smi' — check GPU status, then use /run-experiment in Claude Code to deploy.",
    usageExampleZh: "ssh <host> 'nvidia-smi' — 检查 GPU 状态，然后在 Claude Code 中使用 /run-experiment 部署实验。",
  },
  {
    id: "paper-writing",
    name: "Paper Writing",
    nameZh: "论文写作",
    description: "LaTeX paper generation from experiments",
    descriptionZh: "从实验结果生成 LaTeX 论文",
    category: "research",
    defaultStatus: "active",
    icon: "FileText",
    implType: "skill",
    implDetail: "/paper-writing",
    dependencies: ["aris-pipeline"],
    tier: 4,
    tags: ["latex", "paper"],
  },
  {
    id: "arxiv-search",
    name: "arXiv Search",
    nameZh: "arXiv 搜索",
    description: "Search and download papers from arXiv",
    descriptionZh: "从 arXiv 搜索和下载论文",
    category: "research",
    defaultStatus: "active",
    icon: "Search",
    implType: "skill",
    implDetail: "/arxiv",
    dependencies: ["claude-code"],
    tier: 2,
    tags: ["papers", "search"],
  },
  {
    id: "auto-review",
    name: "Auto Review Loop",
    nameZh: "自动评审循环",
    description: "Multi-round review with external LLM reviewer",
    descriptionZh: "多轮外部 LLM 评审",
    category: "research",
    defaultStatus: "active",
    icon: "RefreshCcw",
    implType: "skill",
    implDetail: "/auto-review-loop",
    dependencies: ["aris-pipeline", "mcp-servers"],
    tier: 4,
    tags: ["review", "iterative"],
  },

  // ==================== MANAGEMENT ====================
  {
    id: "api-keys",
    name: "API Key Manager",
    nameZh: "API Key 管理",
    description: "Multi-provider API key storage and monitoring",
    descriptionZh: "多平台 API Key 存储和监控",
    category: "management",
    defaultStatus: "active",
    icon: "Key",
    implType: "plugin",
    implDetail: "API Management plugin",
    dependencies: ["scc-dashboard"],
    tier: 2,
    tags: ["keys", "billing"],
    pageRoute: "/plugins/api-management",
    usageExample: "Open API Keys page, click '+' to add a key for any provider (OpenAI, Anthropic, DeepSeek, etc.)",
    usageExampleZh: "打开 API 密钥页面，点击 '+' 添加任意提供者的密钥（OpenAI、Anthropic、DeepSeek 等）",
  },
  {
    id: "agent-teams",
    name: "Agent Teams",
    nameZh: "Agent 团队",
    description: "Multi-agent team orchestration with visual canvas",
    descriptionZh: "多 Agent 团队编排，可视化画布",
    category: "management",
    defaultStatus: "active",
    icon: "Users",
    implType: "plugin",
    implDetail: "Agent Teams plugin",
    dependencies: ["scc-dashboard", "claude-code"],
    tier: 3,
    tags: ["agents", "orchestration"],
    pageRoute: "/plugins/agent-teams",
    usageExample: "Open Agent Teams page, create a team from preset or build your own, then run it from the visual canvas.",
    usageExampleZh: "打开 Agent Teams 页面，从预设创建团队或自行构建，然后在可视化画布中运行。",
  },
  {
    id: "task-queue",
    name: "Task Queue",
    nameZh: "任务队列",
    description: "Background task queue management",
    descriptionZh: "后台任务队列管理",
    category: "management",
    defaultStatus: "active",
    icon: "ListTodo",
    implType: "plugin",
    dependencies: ["scc-dashboard"],
    tier: 2,
    tags: ["queue", "background"],
    pageRoute: "/queue",
    usageExample: "Use /bg in Telegram or the Queue button in Chat to add background tasks.",
    usageExampleZh: "在 Telegram 中使用 /bg 或在聊天页面点击队列按钮来添加后台任务。",
  },
  {
    id: "session-manager",
    name: "Session Manager",
    nameZh: "会话管理",
    description: "Browse, search, and manage Claude sessions",
    descriptionZh: "浏览、搜索和管理 Claude 会话",
    category: "management",
    defaultStatus: "active",
    icon: "MessageSquare",
    implType: "plugin",
    dependencies: ["scc-dashboard"],
    tier: 2,
    tags: ["sessions"],
    pageRoute: "/sessions",
    usageExample: "Open Sessions page to browse, search and review past Claude Code sessions.",
    usageExampleZh: "打开会话页面浏览、搜索和查看历史 Claude Code 会话。",
  },
  {
    id: "token-tracking",
    name: "Token Tracking",
    nameZh: "Token 追踪",
    description: "Usage analytics and cost monitoring",
    descriptionZh: "使用量分析和花费监控",
    category: "management",
    defaultStatus: "active",
    icon: "Coins",
    implType: "plugin",
    dependencies: ["scc-dashboard"],
    tier: 2,
    tags: ["tokens", "cost"],
    pageRoute: "/tokens",
    usageExample: "Open Tokens page to view daily cost trends, per-model breakdown, and export CSV reports.",
    usageExampleZh: "打开 Token 页面查看每日费用趋势、按模型分类统计，并导出 CSV 报告。",
  },
  {
    id: "toolbox",
    name: "Toolbox",
    nameZh: "工具箱",
    description: "Manage skills, hooks, agents, rules, MCP servers",
    descriptionZh: "管理技能、钩子、Agent、规则、MCP 服务器",
    category: "management",
    defaultStatus: "active",
    icon: "Wrench",
    implType: "plugin",
    dependencies: ["scc-dashboard"],
    tier: 2,
    tags: ["config"],
    pageRoute: "/toolbox",
    usageExample: "Open Toolbox to manage MCP servers, skills, hooks, agents, and rules — all in one place.",
    usageExampleZh: "打开工具箱管理 MCP 服务器、技能、Hooks、Agent 和规则 — 一站式配置。",
  },

  // ==================== CREATIVE ====================
  {
    id: "video-editing",
    name: "Video Editing",
    nameZh: "视频剪辑",
    description: "AI-assisted video editing and generation",
    descriptionZh: "AI 辅助视频剪辑和生成",
    category: "creative",
    defaultStatus: "planned",
    icon: "Film",
    implType: "planned",
    dependencies: ["claude-code"],
    tier: 4,
    tags: ["video", "content"],
  },
  {
    id: "content-publishing",
    name: "Content Publishing",
    nameZh: "内容发布",
    description: "Automated blog/social media content pipeline",
    descriptionZh: "自动化博客/社交媒体内容流水线",
    category: "creative",
    defaultStatus: "planned",
    icon: "Send",
    implType: "planned",
    dependencies: ["claude-code"],
    tier: 4,
    tags: ["content", "social"],
  },
  {
    id: "pixel-art",
    name: "Pixel Art",
    nameZh: "像素画",
    description: "Generate pixel art SVG illustrations",
    descriptionZh: "生成像素风格 SVG 插图",
    category: "creative",
    defaultStatus: "active",
    icon: "Image",
    implType: "skill",
    implDetail: "/pixel-art",
    dependencies: ["claude-code"],
    tier: 3,
    tags: ["art", "svg"],
  },
  {
    id: "ui-design",
    name: "UI/UX Design",
    nameZh: "UI/UX 设计",
    description: "Frontend design patterns and component creation",
    descriptionZh: "前端设计模式和组件创建",
    category: "creative",
    defaultStatus: "active",
    icon: "Palette",
    implType: "skill",
    implDetail: "/frontend-patterns",
    dependencies: ["claude-code", "nodejs"],
    tier: 3,
    tags: ["design", "frontend"],
  },

  // ==================== INTEGRATION ====================
  {
    id: "telegram-bot",
    name: "Telegram Bot",
    nameZh: "Telegram 机器人",
    description: "Chat with Claude via Telegram, approval workflows",
    descriptionZh: "通过 Telegram 与 Claude 对话，审批工作流",
    category: "integration",
    defaultStatus: "configurable",
    icon: "MessageCircle",
    implType: "api",
    implDetail: "TELEGRAM_BOT_TOKEN env var",
    dependencies: ["scc-dashboard"],
    tier: 3,
    tags: ["bot", "mobile", "telegram"],
    setupGuide: "Set TELEGRAM_BOT_TOKEN from @BotFather",
    setupSteps: [
      "Open @BotFather on Telegram, create a bot with /newbot",
      "Copy the bot token",
      "Go to Settings > Bots > Telegram, paste the token",
      "Choose Polling mode (no public URL needed) or Webhook mode",
      "Click Start Polling to test",
    ],
    detectCommand: "node -e \"fetch('http://localhost:3000/api/bot/telegram').then(r=>r.json()).then(d=>process.exit(d.configured?0:1)).catch(()=>process.exit(1))\"",
    detectHint: "Settings > Bots > Telegram shows 'Connected'",
    pageRoute: "/settings",
    configFields: [
      {
        key: "botToken",
        label: "Bot Token",
        labelZh: "Bot Token",
        type: "text",
        placeholder: "123456:ABC-DEF...",
      },
      {
        key: "chatId",
        label: "Allowed Chat IDs",
        labelZh: "允许的 Chat ID",
        type: "text",
        placeholder: "123456789 (comma-separated)",
      },
    ],
    usageExample: "In Claude Code, use /feishu-notify or configure in Settings > Bots > Telegram. Send a test: curl -X POST http://localhost:3000/api/bot/telegram -d '{\"message\":\"Hello from SCC!\"}'",
    usageExampleZh: "在 Claude Code 中使用 /feishu-notify 或在设置 > 机器人 > Telegram 中配置。发送测试：curl -X POST http://localhost:3000/api/bot/telegram -d '{\"message\":\"Hello from SCC!\"}'",
  },
  {
    id: "feishu-bot",
    name: "Feishu / Lark Bot",
    nameZh: "飞书机器人",
    description: "Feishu integration for team notifications",
    descriptionZh: "飞书集成，团队通知",
    category: "integration",
    defaultStatus: "configurable",
    icon: "MessageSquare",
    implType: "api",
    implDetail: "FEISHU_APP_ID + FEISHU_APP_SECRET",
    dependencies: ["scc-dashboard"],
    tier: 3,
    tags: ["bot", "feishu", "notification"],
    setupGuide: "Create app at open.feishu.cn",
    setupSteps: [
      "Go to open.feishu.cn, create an app",
      "Enable 'Bot' capability and 'Event Subscription'",
      "Copy App ID and App Secret",
      "Go to Settings > Bots > Feishu, paste credentials",
      "Set webhook URL in Feishu app console",
    ],
    detectCommand: "node -e \"fetch('http://localhost:3000/api/bot/feishu').then(r=>r.json()).then(d=>process.exit(d.configured?0:1)).catch(()=>process.exit(1))\"",
    detectHint: "Settings > Bots > Feishu shows 'Connected'",
    pageRoute: "/settings",
    configFields: [
      {
        key: "appId",
        label: "App ID",
        labelZh: "App ID",
        type: "text",
        placeholder: "cli_xxxxxxxxxxxx",
      },
      {
        key: "appSecret",
        label: "App Secret",
        labelZh: "App Secret",
        type: "text",
        placeholder: "xxxxxxxxxxxxxxxx",
      },
    ],
    usageExample: "Go to Settings > Bots > Feishu, enter credentials. Test: send a notification via ARIS pipeline completion.",
    usageExampleZh: "前往设置 > 机器人 > 飞书，输入凭据。测试：通过 ARIS 流水线完成时发送通知。",
  },
  {
    id: "mobile-access",
    name: "Mobile Access",
    nameZh: "手机访问",
    description: "PWA + responsive design for mobile access",
    descriptionZh: "PWA + 响应式设计，手机可访问",
    category: "integration",
    defaultStatus: "active",
    icon: "Smartphone",
    implType: "plugin",
    dependencies: ["scc-dashboard"],
    tier: 2,
    tags: ["mobile", "pwa"],
  },
  {
    id: "discord-bot",
    name: "Discord Bot",
    nameZh: "Discord 机器人",
    description: "Discord integration for communities",
    descriptionZh: "Discord 社区集成",
    category: "integration",
    defaultStatus: "planned",
    icon: "Hash",
    implType: "planned",
    dependencies: ["scc-dashboard"],
    tier: 4,
    tags: ["bot", "discord"],
  },
  {
    id: "pipeline-notify",
    name: "Pipeline Notifications",
    nameZh: "流水线通知",
    description: "Push notifications on pipeline events",
    descriptionZh: "流水线事件推送通知",
    category: "integration",
    defaultStatus: "active",
    icon: "Bell",
    implType: "plugin",
    implDetail: "src/lib/execution/notifier.ts",
    dependencies: ["telegram-bot", "feishu-bot"],
    tier: 3,
    tags: ["notification"],
  },

  // ==================== ADVANCED ====================
  {
    id: "skill-creator",
    name: "Skill Creator",
    nameZh: "技能创建器",
    description: "AI-powered skill/command generator",
    descriptionZh: "AI 驱动的技能/命令生成器",
    category: "advanced",
    defaultStatus: "active",
    icon: "Wand2",
    implType: "plugin",
    dependencies: ["scc-dashboard", "claude-code"],
    tier: 3,
    tags: ["meta", "generator"],
    pageRoute: "/toolbox",
    usageExample: "Go to Toolbox > Skills tab, click 'AI Create' to generate a new skill from a description.",
    usageExampleZh: "前往工具箱 > 技能标签页，点击「AI 创建」从描述生成新技能。",
  },
  {
    id: "mcp-generator",
    name: "MCP Generator",
    nameZh: "MCP 生成器",
    description: "Generate custom MCP servers from descriptions",
    descriptionZh: "从描述生成自定义 MCP 服务器",
    category: "advanced",
    defaultStatus: "planned",
    icon: "Boxes",
    implType: "planned",
    dependencies: ["mcp-servers", "skill-creator"],
    tier: 4,
    tags: ["meta", "mcp", "generator"],
  },
  {
    id: "qa-knowledge-base",
    name: "Q&A Knowledge Base",
    nameZh: "问答知识库",
    description: "Interactive Q&A for learning SCC features",
    descriptionZh: "交互式问答，学习 SCC 功能",
    category: "advanced",
    defaultStatus: "planned",
    icon: "HelpCircle",
    implType: "planned",
    dependencies: ["scc-dashboard"],
    tier: 3,
    tags: ["help", "onboarding"],
  },
  {
    id: "stock-trading",
    name: "Stock Trading",
    nameZh: "股票交易",
    description: "AI-assisted market analysis and trading signals",
    descriptionZh: "AI 辅助市场分析和交易信号",
    category: "advanced",
    defaultStatus: "planned",
    icon: "TrendingUp",
    implType: "planned",
    dependencies: ["api-keys", "claude-code"],
    tier: 5,
    tags: ["finance", "trading"],
  },
  {
    id: "daily-briefing",
    name: "Daily Intelligence",
    nameZh: "每日情报简报",
    description: "GitHub Trending + HF Papers + RSS digest",
    descriptionZh: "GitHub 趋势 + HF 论文 + RSS 摘要",
    category: "advanced",
    defaultStatus: "planned",
    icon: "Newspaper",
    implType: "planned",
    dependencies: ["scc-dashboard", "telegram-bot"],
    tier: 4,
    tags: ["digest", "news"],
  },
  {
    id: "freelance-platform",
    name: "Freelance Automation",
    nameZh: "全网接单",
    description: "Auto-bid, sandbox execute, deliver on freelance platforms",
    descriptionZh: "自动投标、沙箱执行、交付到自由职业平台",
    category: "advanced",
    defaultStatus: "planned",
    icon: "Briefcase",
    implType: "planned",
    dependencies: ["agent-teams", "api-keys", "security-scan"],
    tier: 5,
    tags: ["freelance", "automation"],
  },
  {
    id: "skill-tree-meta",
    name: "Skill Tree",
    nameZh: "技能树",
    description: "This skill tree visualization itself",
    descriptionZh: "这个技能树可视化本身",
    category: "advanced",
    defaultStatus: "active",
    icon: "TreePine",
    implType: "plugin",
    dependencies: ["scc-dashboard"],
    tier: 2,
    tags: ["meta", "visualization"],
  },

  // ==================== OTHER ====================
  {
    id: "docker",
    name: "Docker",
    nameZh: "Docker 容器",
    description: "Container management and deployment",
    descriptionZh: "容器管理和部署",
    category: "other",
    defaultStatus: "configurable",
    icon: "Boxes",
    implType: "cli",
    dependencies: [],
    tier: 2,
    tags: ["devops", "container"],
    detectCommand: "docker --version",
    setupSteps: [
      "Windows: Install Docker Desktop from docker.com | Linux: sudo apt install docker.io (or snap install docker)",
      "Windows: Start Docker Desktop | Linux: sudo systemctl start docker",
      "Verify: docker --version",
    ],
    usageExample: "docker run hello-world (verify installation works)",
    usageExampleZh: "docker run hello-world（验证安装是否成功）",
  },
  {
    id: "ssh-remote",
    name: "SSH Remote",
    nameZh: "SSH 远程",
    description: "Remote server access for experiments",
    descriptionZh: "远程服务器访问（实验用）",
    category: "other",
    defaultStatus: "configurable",
    icon: "Globe",
    implType: "manual",
    dependencies: [],
    tier: 2,
    tags: ["remote", "server"],
    detectCommand: "ssh -V",
    setupSteps: [
      "Generate keys: ssh-keygen -t ed25519 (works on both Windows and Linux)",
      "Windows: Edit C:\\Users\\<you>\\.ssh\\config | Linux: Edit ~/.ssh/config",
      "Test connection: ssh <host> \"echo ok\"",
    ],
    detectHint: "Windows: Check C:\\Users\\<you>\\.ssh\\config | Linux: Check ~/.ssh/config",
    usageExample: "ssh <host> 'nvidia-smi' — check GPU status on remote server",
    usageExampleZh: "ssh <host> 'nvidia-smi' — 检查远程服务器 GPU 状态",
  },
  {
    id: "database",
    name: "Database",
    nameZh: "数据库",
    description: "Database management (SQLite, PostgreSQL)",
    descriptionZh: "数据库管理（SQLite、PostgreSQL）",
    category: "other",
    defaultStatus: "planned",
    icon: "Database",
    implType: "planned",
    dependencies: [],
    tier: 3,
    tags: ["data", "sql"],
  },
  {
    id: "clipboard-sync",
    name: "Clipboard Sync",
    nameZh: "剪贴板同步",
    description: "Cross-device clipboard sharing",
    descriptionZh: "跨设备剪贴板共享",
    category: "other",
    defaultStatus: "planned",
    icon: "Clipboard",
    implType: "planned",
    dependencies: [],
    tier: 4,
    tags: ["utility", "sync"],
  },
];
